spring:
  application:
    name: service-zuul
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
#      serviceId: hiapi-v1
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  prefix: /v1
#ribbon:
#  eureka:
#    enabled: false
#hiapi-v1:
#  ribbon:
#    listOfServers: http://localhost:8762,http://localhost:8763