spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
