spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://{ip}:{port}/spring-security?userUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
