spring:
  application:
    name: eureka-feign-client
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
feign:
  hystrix:
    enabled: true